export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RESTRICTED_SUCCESS = "RESTRICTED_SUCCESS";
export const RESTRICTED_FAILED = "RESTRICTED_FAILED";

export const GET_STATISTIC_SUCCESS = "GET_STATISTIC_SUCCESS"
export const GET_STATISTIC_FAILED = "GET_STATISTIC_FAILED"